### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by MikeCZ23** [Vaminta/papas-save-manager#1]
crazygames problem export saves
![Snímek obrazovky 2024-05-11 135911](https://github.com/Vaminta/papas-save-manager/assets/45541448/827ad2c2-1c56-4df5-b57c-8fed85f527ca)

coolmathgames no allow export saves

these game missing:
Donuteria
Pizzeria
Scooperia

**Comment by Vaminta** [comment]
Thank you for reporting this bug. The cause has been found and an update has been released. Please see the updated readme file for any potential problems you may have following this update.  Regarding the screenshot above: the in-game option to export saves does not work so please use the PSM box visible below the game window. Please do not hesitate to contact if you have any further problems!
